#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,3,9,45,49,50,53&i=22,23,24&v=32,33,34 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* OneButton */

/* !!! Do not be alarmed, all right, the default values вЂ‹вЂ‹are not included in this file !!! */

#define L10N_LANGUAGE			RU
#define I2S_INTERNAL			true
#define BTN_LEFT			32
#define BTN_CENTER			33
#define BTN_RIGHT			34


#endif
